# Generated by Django 3.2.2 on 2021-05-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholder',
            name='username',
            field=models.TextField(),
        ),
    ]
