# Generated by Django 3.2.2 on 2021-05-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0002_alter_stockholder_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockholder',
            name='asset_value',
        ),
    ]
