# Generated by Django 3.2.2 on 2021-05-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0003_remove_stockholder_asset_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholder',
            name='buying_power',
            field=models.FloatField(),
        ),
    ]
